"""initial schema

Revision ID: 8ec63943ed39
Revises: 
Create Date: 2026-08-07 08:54:59.709183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec63943ed39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_registry',
    sa.Column('cg_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('binance_symbol', sa.String(length=64), nullable=True),
    sa.Column('binance_state', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cg_id')
    )
    op.create_index(op.f('ix_asset_registry_symbol'), 'asset_registry', ['symbol'], unique=False)
    op.create_table('ingest_state',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('last_daily_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('ohlcv_bars',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'interval')
    )
    op.create_index('ix_ohlcv_symbol_timestamp', 'ohlcv_bars', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ohlcv_symbol_timestamp', table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_table('ingest_state')
    op.drop_index(op.f('ix_asset_registry_symbol'), table_name='asset_registry')
    op.drop_table('asset_registry')
    # ### end Alembic commands ###
